"""Create database

Revision ID: 8e3138907201
Revises: 
Create Date: 2023-04-06 23:28:55.385246
"""

from alembic import op
import sqlalchemy as sa


revision = "8e3138907201"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "control",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("person_name", sa.String(), nullable=False),
        sa.Column("identity_name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "person_name", "identity_name", name="bridge_person_identity"
        ),
    )
    op.create_table(
        "identities",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("avatar", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "people",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("avatar", sa.String(), nullable=False),
        sa.Column("password", sa.LargeBinary(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "clients",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("creator_name", sa.String(), nullable=False),
        sa.Column("client_id", sa.String(length=48), nullable=True),
        sa.Column("client_secret", sa.String(length=120), nullable=True),
        sa.Column("client_id_issued_at", sa.Integer(), nullable=False),
        sa.Column("client_secret_expires_at", sa.Integer(), nullable=False),
        sa.Column("client_metadata", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["creator_name"],
            ["people.name"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_clients_client_id"), "clients", ["client_id"], unique=False
    )
    op.create_table(
        "people_tokens",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("identity_name", sa.String(), nullable=False),
        sa.Column("client_id", sa.String(length=48), nullable=True),
        sa.Column("token_type", sa.String(length=40), nullable=True),
        sa.Column("access_token", sa.String(length=255), nullable=False),
        sa.Column("refresh_token", sa.String(length=255), nullable=True),
        sa.Column("scope", sa.Text(), nullable=True),
        sa.Column("issued_at", sa.Integer(), nullable=False),
        sa.Column("access_token_revoked_at", sa.Integer(), nullable=False),
        sa.Column("refresh_token_revoked_at", sa.Integer(), nullable=False),
        sa.Column("expires_in", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["identity_name"],
            ["identities.name"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("access_token"),
    )
    op.create_index(
        op.f("ix_people_tokens_refresh_token"),
        "people_tokens",
        ["refresh_token"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_people_tokens_refresh_token"), table_name="people_tokens")
    op.drop_table("people_tokens")
    op.drop_index(op.f("ix_clients_client_id"), table_name="clients")
    op.drop_table("clients")
    op.drop_table("people")
    op.drop_table("identities")
    op.drop_table("control")
    # ### end Alembic commands ###
